# Generated by Django 5.0.6 on 2024-08-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0020_alter_venue_district_alter_venue_municipality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "request_sent_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Request Sent Date"
                    ),
                ),
                (
                    "request_accepted_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Request Sent Date"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "BookingInfo",
                "verbose_name_plural": "BookingInfos",
                "managed": True,
            },
        ),
    ]
