# Generated by Django 5.0.6 on 2024-08-13 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_venue_district_alter_venue_municipality_and_more"),
        ("booking", "0002_alter_bookinginfo_request_accepted_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginfo",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="bookinginfo",
            name="date",
            field=models.DateField(verbose_name="Booking Date"),
        ),
        migrations.AlterField(
            model_name="bookinginfo",
            name="request_accepted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Request Accepted Date"
            ),
        ),
    ]
