# Generated by Django 5.0.6 on 2024-08-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_venue_district_alter_venue_municipality_and_more"),
        ("booking", "0003_alter_bookinginfo_customer_alter_bookinginfo_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinginfo",
            name="request_rejected_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Request Rejected Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookinginfo",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_details",
                to="accounts.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="bookinginfo",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_details",
                to="accounts.venue",
                verbose_name="Venue",
            ),
        ),
    ]
