# Generated by Django 5.0.6 on 2024-06-05 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_num", models.IntegerField(verbose_name="phone number")),
                (
                    "terms_condition",
                    models.BooleanField(verbose_name="Terms & Condition"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="Full name"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auth user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_num", models.IntegerField(verbose_name="phone number")),
                (
                    "terms_condition",
                    models.BooleanField(verbose_name="Terms & Condition"),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=50, verbose_name="organization name"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auth user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
