# Generated by Django 5.0.6 on 2024-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="terms_condition",
            field=models.BooleanField(default=False, verbose_name="Terms & Condition"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="terms_condition",
            field=models.BooleanField(default=False, verbose_name="Terms & Condition"),
        ),
    ]
