# Generated by Django 5.0.6 on 2024-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customer_terms_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_num",
            field=models.IntegerField(unique=True, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone_num",
            field=models.IntegerField(unique=True, verbose_name="phone number"),
        ),
    ]
