# Generated by Django 5.0.6 on 2024-06-05 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_phone_num_alter_venue_phone_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="pan_no",
            field=models.IntegerField(blank=True, null=True, verbose_name="Pan Number"),
        ),
        migrations.AddField(
            model_name="venue",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Photo 1 "
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
                verbose_name="Video 1",
            ),
        ),
    ]
