# Generated by Django 5.0.6 on 2024-06-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_venue_pan_no_venue_photo_venue_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="photo",
            new_name="photo1",
        ),
        migrations.RenameField(
            model_name="venue",
            old_name="video",
            new_name="video1",
        ),
    ]
