# Generated by Django 5.0.6 on 2024-06-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_photo_venue_photo1_rename_video_venue_video1"),
        ("nepali_address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.district",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="municipality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.municipality",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.province",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="ward",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
