# Generated by Django 5.0.6 on 2024-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_venue_district_venue_municipality_venue_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="pan_no",
            field=models.IntegerField(
                blank=True, max_length=9, null=True, verbose_name="Pan Number"
            ),
        ),
    ]
