# Generated by Django 5.0.6 on 2024-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_venue_pan_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="pan_no",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Pan Number"
            ),
        ),
    ]
