# Generated by Django 5.0.6 on 2024-06-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_venue_property_type"),
        ("nepali_address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.district",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nepali_address.province",
            ),
        ),
    ]
