# Generated by Django 5.0.6 on 2024-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_venue_district_alter_venue_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Party Palace", "Party Palace"),
                    ("1", "Resort"),
                    ("Restaurant", "Restaurant"),
                    ("Lounge", "Lounge"),
                    ("Community Hall", "Community Hall"),
                    ("Office Space", "Office Space"),
                ],
                max_length=50,
                null=True,
                verbose_name="Property Type",
            ),
        ),
    ]
