# Generated by Django 5.0.6 on 2024-06-10 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_venue_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="isSubscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="photo2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="Subscription Photo",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="social1",
            field=models.URLField(null=True, verbose_name="URL 1"),
        ),
        migrations.AddField(
            model_name="venue",
            name="social2",
            field=models.URLField(null=True, verbose_name="URL 2"),
        ),
        migrations.AddField(
            model_name="venue",
            name="social3",
            field=models.URLField(null=True, verbose_name="URL 3"),
        ),
        migrations.AddField(
            model_name="venue",
            name="video2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
                verbose_name="Subscription Video",
            ),
        ),
    ]
