# Generated by Django 5.0.6 on 2024-06-15 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_venue_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="rating",
            field=models.IntegerField(
                blank=True, max_length=5, null=True, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="seat_capacity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Seat Capacity"
            ),
        ),
    ]
