# Generated by Django 5.0.6 on 2024-06-15 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_venue_price_venue_rating_venue_seat_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
