# Generated by Django 5.0.6 on 2024-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_venue_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="social1",
            field=models.URLField(blank=True, null=True, verbose_name="URL 1"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="social2",
            field=models.URLField(blank=True, null=True, verbose_name="URL 2"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="social3",
            field=models.URLField(blank=True, null=True, verbose_name="URL 3"),
        ),
    ]
