# Generated by Django 5.0.6 on 2024-06-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_venue_social1_alter_venue_social2_and_more"),
        ("nepali_address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nepali_address.district",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nepali_address.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nepali_address.province",
            ),
        ),
    ]
