# Generated by Django 5.0.6 on 2024-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_venue_district_alter_venue_municipality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="district",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="municipality",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="province",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="ward",
        ),
        migrations.AddField(
            model_name="venue",
            name="address",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Venue Address"
            ),
        ),
    ]
